### ISSUE TITLE
Crash on Startup v0.7

### ISSUE THREAD

**Issue by Trent2087** [RecraftorsMC/Dumpster#12]
Crashes on startup on client, All of Fabric 6 modpack. Does not crash on server.
https://hastebin.com/share/sejadopaba.rust

[10:58:57] [main/ERROR]: Mixin apply for mod dumpster failed dumpster.mixins.json:client.ClientPlayerEntityMixin from mod dumpster 
-> net.minecraft.client.network.ClientPlayerEntity: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException 
Critical injection failure: @Inject annotation on onSendCommandBeforeSendInjector could not find any targets matching 
'Lnet/minecraft/ClientPlayerEntity;sendCommandInternal(Lnet/minecraft/MessageMetadata;Ljava/lang/String;Lnet/minecraft/Text;)V'

v0.6 works.

**Comment by RecraftorsTeam** [comment]
Hello,

Thank you for letting us know about this issue.

Sadly, it appears it is due to the vanilla game changing their way to handle commands on the client between 1.19 and 1.19.2, or 1.19.1 (tests would be required to know more about that, but since 1.19.1 is pretty much a ghost version on the modding scene, we will not spend time adapting to it unless someone signals it to us)

But as our current focus is to implement all functionality first, before moving to porting them to other game versions, we shall simply disable the affected mixins when the mod is loaded on 1.19.2, so that the issue no longer arises. Sadly, this also means completely disabling the client command on the affected versions. But since this one is not as relevant as the server-side one, or even can be perceived as a way to access data that supposedly should remain only known to the server, this will not be perceived as a real loss. Thank you for your comprehension.

We shall then haste ourselves to make a new version, that will include the aforementioned fix to the issue you made us aware of.

Regards,

The Recraftors team.
